=== shelldudu/never_application/src/admin/B2C.Admin.Taskschd/App_Config/easysql.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="never.easysql"
           elementFormDefault="qualified"
           xmlns:mstns="http://tempuri.org/XMLSchema.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="never.easysql">

  <xs:element name="namespace">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="sql" maxOccurs="unbounded" />
        <xs:element ref="select" maxOccurs="unbounded" />
        <xs:element ref="delete" maxOccurs="unbounded" />
        <xs:element ref="update" maxOccurs="unbounded" />
        <xs:element ref="insert" maxOccurs="unbounded" />
        <xs:element ref="procedure" maxOccurs="unbounded" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>

  <xs:element name="procedure">
    <xs:complexType mixed="true">
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="include">
    <xs:complexType mixed="true">
      <xs:attribute name="refid" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="sql">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="return" maxOccurs="0" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="select">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="if" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="delete">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="if" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="insert">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="return" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="return">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="type" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:NMTOKEN">
                <xs:enumeration value="byte" />
                <xs:enumeration value="char" />
                <xs:enumeration value="datetime" />
                <xs:enumeration value="decimal" />
                <xs:enumeration value="double" />
                <xs:enumeration value="float" />
                <xs:enumeration value="int" />
                <xs:enumeration value="short" />
                <xs:enumeration value="guid" />
                <xs:enumeration value="string" />
                <xs:enumeration value="other" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="update">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="return" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>

  <xs:element name="if">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="then" type="xs:string" use="required" />
      <xs:attribute name="end" type="xs:string" use="required" />
      <xs:attribute name="split" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifnotnull">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifnotempty">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifnull">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifempty">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifcontain">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="ifarray">
    <xs:complexType mixed="true">
      <xs:attribute name="open" type="xs:string" use="required" />
      <xs:attribute name="close" type="xs:string" use="required" />
      <xs:attribute name="split" type="xs:string" use="required" />
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/Permissions/Repository/Xml/MySql/GroupResource.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="mysql" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <insert id="batchInsertGroupResourceRoot">
    insert into group_resource
    (AggregateId,
    GroupId,
    ResourceId,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    <ifarray open="" close="" parameter="" split="," then="">
      (@AggregateId,
      @GroupId,
      @ResourceId,
      @CreateDate,
      @Creator,
      @EditDate,
      @Editor,
      @Version)
    </ifarray>
  </insert>

  <select id="qryGroupResourceRoot">
    select gr.* from resource as a inner join group_resource as gr on a.AggregateId = gr.ResourceId
    where gr.GroupId = @GroupId;
  </select>
  
  <select id="qryResourceRootOfGroup">
    select a.* from resource as a inner join group_resource as gr on a.AggregateId = gr.ResourceId
    where gr.GroupId = @GroupId;
  </select>
  
  <select id="qryGroupOwnerResourceRoot">
    select a.*,
    (select DepartmentId from group_resource as gr where a.AggregateId = gr.ResourceId and gr.GroupId = @GroupId) as OwnerId
    from resource as a inner join department_resource as dr on a.AggregateId = dr.ResourceId
    where a.GroupSort = 0
    and dr.DepartmentId = @DepartmentId
  </select>
  
  <delete id="batchDeleteGroupResourceRoot">
    delete from group_resource
    <if then="where" end="" split="">
      <ifarray open="" close="" parameter="AggregateId" split="," then="">
        AggregateId in (@AggregateId)
      </ifarray>
      <ifarray open="" close="" parameter="ResourceId" split="," then="">
        ResourceId in (@ResourceId)
      </ifarray>
    </if>
  </delete>
</namespace>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/Permissions/Repository/Xml/SqlServer/Department.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="sqlserver" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <insert id="insertDepartmentRoot">
    insert into department
    (AggregateId,
    Name,
    Descn,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    (@AggregateId,
    @Name,
    @Descn,
    @CreateDate,
    @Creator,
    @EditDate,
    @Editor,
    @Version);
    <return type="int">
      select @@Identity;
    </return>
  </insert>

  <select id="qryDepartmentRoot">
    select a.* from department as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
    </if>
  </select>

  <select id="qry_DepartmentRoot">
    select p.* from (select row_number() over (order by id desc) as _, a.* from department as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
    </if> ) as p where p._ >= @StartIndex and p._ &lt;= @EndIndex
  </select>

  <select id="qryDepartmentRootCount">
    select count(a.Id) from department as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
    </if>
  </select>

  <update id="updateDepartmentRoot">
    update department
    set Version = Version + 1,
    Name = @Name,
    Descn = @Descn,
    EditDate = @EditDate,
    Editor = @Editor
    where AggregateId = @AggregateId
    and Version = @Version;
  </update>

  <delete id="deleteDepartmentRoot">
    delete from department
    where AggregateId = @AggregateId
    and Version = @Version;
  </delete>
</namespace>

=== shelldudu/never_application/src/message/B2C.Message.SqlData/Repository/Xml/SqlServer/MobileCodeRepository.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="sqlserver.repos" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <select id="qryMobileCodeRoot">
    select a.* from mobile_code as a
    <if then="where" end="" split="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Mobile" then="and">
        a.Mobile = @Mobile
      </ifnotnull>
      <ifnotnull parameter="UsageType" then="and">
        a.UsageType = @UsageType
      </ifnotnull>
      <ifnotnull parameter="UsageStatus" then="and">
        a.UsageStatus= @UsageStatus
      </ifnotnull>
    </if>
    order by a.Id desc
  </select>

  <insert id="insertMobileCodeRoot">
    INSERT INTO mobile_code
    (AggregateId,
    Mobile,
    UsageType,
    UsageCode,
    ExpireTime,
    UsageStatus,
    ClientIP,
    Platform,
    CreateDate,
    Creator,
    EditDate ,
    Editor ,
    Version)
    VALUES
    (@AggregateId,
    @Mobile,
    @UsageType,
    @UsageCode,
    @ExpireTime,
    @UsageStatus,
    @ClientIP,
    @Platform,
    @CreateDate,
    @Creator,
    @EditDate,
    @Editor,
    @Version);
    <return type="int">
      select @@Identity as value;
    </return>
  </insert>

  <update id="updateMobileCodeUsed">
    update mobile_code
    set Version = Version +1,
    UsageStatus = @UsageStatus,
    EditDate = @EditDate,
    Editor = @Editor
    where AggregateId = @AggregateId
    and UsageStatus = 0
    and ExpireTime &gt; Getdate();
  </update>
</namespace>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/App_Config/easysqldemo.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="demo"
           indented="true"
           xmlns="never.easysql"
           xsi:schemaLocation="never.easysql easysql.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <sql id="sqlUserAllField">
    select a.Id,
    a.UserId,
    a.UserName
    from myuser as a
  </sql>

  <sql id="qryUserContion">
    <ifnotnull parameter="UserId" then="and">
      UserId = $UserId$ and UserId = @UserId
    </ifnotnull>
    <ifnotnull parameter="Id" then="and">
      Id = @Id
    </ifnotnull>
    <ifempty parameter="UserName" then="and">
      UserName = '111'
    </ifempty>
    <ifnotempty parameter="UserName" then="and">
      UserName = '222'
    </ifnotempty>
  </sql>

  <select id="qryUser">
    <include refid="sqlUserAllField"></include>
    <if then="where" end=";" split="">
      <include refid="qryUserContion"></include>
      <ifarray parameter="IdArray" then="and" split="," open="" close="">
        Id in (@IdArray)
      </ifarray>
    </if>
  </select>

  <delete id="delUser">
    delete from myuser
    where UserId = @UserId;
  </delete>

  <update id="updUser">
    update myuser
    set UserName = @UserName
    where UserId = @UserId;
  </update>

  <insert id="insUser">
    insert into myuser(UserId,UserName)
    values(
    @UserId,
    @UserName);
    <return type="int">
      select @@identity;
    </return>
  </insert>

  <insert id="batchInsUser">
    insert into myuser(UserId,UserName)
    values
    <ifarray open = "(" close= ")" parameter = "" then = "" split = ",">
      @UserId,
      @UserName
    </ifarray>
  </insert>
</namespace>

=== shelldudu/never_application/src/message/B2C.Message.SqlData/Query/Xml/SqlServer/MobileCodeQuery.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="sqlserver.query" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <sql id="qryMobileCodeScout">
    <ifnotnull parameter="AggregateId" then="and">
      a.AggregateId = @AggregateId
    </ifnotnull>
    <ifnotnull parameter="Mobile" then="and">
      a.Mobile = @Mobile
    </ifnotnull>
    <ifnotnull parameter="ClientIP" then="and">
      a.ClientIP = @ClientIP
    </ifnotnull>
    <ifnotnull parameter="UsageType" then="and">
      a.UsageType = @UsageType
    </ifnotnull>
    <ifnotnull parameter="UsageStatus" then="and">
      a.UsageStatus= @UsageStatus
    </ifnotnull>
    <ifnotnull parameter="BeginTime" then="and">
      a.CreateDate >= @BeginTime
    </ifnotnull>
    <ifnotnull parameter="EndTime" then="and">
      a.CreateDate &lt; @EndTime
    </ifnotnull>
  </sql>
  
  <select id="qryMobileCodeInfo">
    select a.* from mobile_code as a
    <if then="where" end="" split="">
      <include refid="qryMobileCodeScout"></include>
    </if>
    <ifnotnull parameter="OrderBy" then="">
      $OrderBy$
    </ifnotnull>
    <ifnull parameter="OrderBy" then="">
      order by a.Id desc
    </ifnull>
  </select>
  
  <select id="qry_MobileCodeInfo">
    select p.* from (select row_number() over (
    <ifnotnull parameter="OrderBy" then="">
      $OrderBy$
    </ifnotnull>
    <ifnull parameter="OrderBy" then="">
      order by a.Id desc
    </ifnull>
    ) as _,   a.* from mobile_code as a
    <if then="where" end="" split="">
      <include refid="qryTemplateInfoScout"></include>
    </if>
    ) as p where p._ >= @StartIndex and p._ &lt;= @EndIndex
  </select>
  
  <select id="qryMobileCodeInfoCount">
    select count(a.Id) from mobile_code as a
    <if then="where" end="" split="">
      <include refid="qryMobileCodeScout"></include>
    </if>
  </select>
</namespace>
