=== shelldudu/never_application/src/admin/B2C.Admin.Taskschd/App_Config/easysql.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="never.easysql"
           elementFormDefault="qualified"
           xmlns:mstns="http://tempuri.org/XMLSchema.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="never.easysql">

  <xs:element name="namespace">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="sql" maxOccurs="unbounded" />
        <xs:element ref="select" maxOccurs="unbounded" />
        <xs:element ref="delete" maxOccurs="unbounded" />
        <xs:element ref="update" maxOccurs="unbounded" />
        <xs:element ref="insert" maxOccurs="unbounded" />
        <xs:element ref="procedure" maxOccurs="unbounded" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>

  <xs:element name="procedure">
    <xs:complexType mixed="true">
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="include">
    <xs:complexType mixed="true">
      <xs:attribute name="refid" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="sql">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="return" maxOccurs="0" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="select">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="if" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="delete">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="if" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="insert">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="return" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="return">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="type" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:NMTOKEN">
                <xs:enumeration value="byte" />
                <xs:enumeration value="char" />
                <xs:enumeration value="datetime" />
                <xs:enumeration value="decimal" />
                <xs:enumeration value="double" />
                <xs:enumeration value="float" />
                <xs:enumeration value="int" />
                <xs:enumeration value="short" />
                <xs:enumeration value="guid" />
                <xs:enumeration value="string" />
                <xs:enumeration value="other" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="update">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="return" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="indented" type="xs:boolean" />
    </xs:complexType>
  </xs:element>

  <xs:element name="if">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="include" />
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="then" type="xs:string" use="required" />
      <xs:attribute name="end" type="xs:string" use="required" />
      <xs:attribute name="split" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifnotnull">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifnotempty">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifnull">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifempty">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ifcontain">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ifnotnull" />
        <xs:element ref="ifnull" />
        <xs:element ref="ifnotempty" />
        <xs:element ref="ifempty" />
        <xs:element ref="ifcontain" />
        <xs:element ref="ifarray" />
      </xs:choice>
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="ifarray">
    <xs:complexType mixed="true">
      <xs:attribute name="open" type="xs:string" use="required" />
      <xs:attribute name="close" type="xs:string" use="required" />
      <xs:attribute name="split" type="xs:string" use="required" />
      <xs:attribute name="parameter" type="xs:string" use="required" />
      <xs:attribute name="then" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== shelldudu/never_application/src/message/B2C.Message.SqlData/Repository/Xml/MySql/EmailCodeRepository.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="mysql.repos" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <select id="qryEmailCodeRoot">
    select a.* from email_code as a
    <if then="where" end="" split="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Email" then="and">
        a.Email = @Email
      </ifnotnull>
      <ifnotnull parameter="UsageType" then="and">
        a.UsageType = @UsageType
      </ifnotnull>
      <ifnotnull parameter="UsageStatus" then="and">
        a.UsageStatus= @UsageStatus
      </ifnotnull>
    </if>
    order by a.Id desc
  </select>

  <insert id="insertEmailCodeRoot">
    INSERT INTO email_code
    (AggregateId,
    Email,
    UsageType,
    UsageCode,
    ExpireTime,
    UsageStatus,
    ClientIP,
    Platform,
    CreateDate,
    Creator,
    EditDate ,
    Editor ,
    Version)
    VALUES
    (@AggregateId,
    @Email,
    @UsageType,
    @UsageCode,
    @ExpireTime,
    @UsageStatus,
    @ClientIP,
    @Platform,
    @CreateDate,
    @Creator,
    @EditDate,
    @Editor,
    @Version);
    <return type="int">
      select last_insert_id() as Id;
    </return>
  </insert>

  <update id="updateEmailCodeUsed">
    update email_code
    set Version = Version +1,
    UsageStatus = @UsageStatus,
    EditDate = @EditDate,
    Editor = @Editor
    where AggregateId = @AggregateId
    and UsageStatus = 0
    and ExpireTime &lt; now();
  </update>
</namespace>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/Permissions/Repository/Xml/MySql/Resource.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="mysql" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <insert id="insertResourceRoot">
    insert into resource
    (AggregateId,
    GroupSort,
    ActionDescn,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    (@AggregateId,
    @GroupSort,
    @ActionDescn,
    @CreateDate,
    @Creator,
    @EditDate,
    @Editor,
    @Version);
    <return type="int">
      select last_insert_id() as Id;
    </return>
  </insert>

  <insert id="batchInsertResourceRoot">
    insert into resource
    (AggregateId,
    GroupSort,
    ActionDescn,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    <ifarray open="" close="" parameter="" split="," then="">
      (@AggregateId,
      @GroupSort,
      @ActionDescn,
      @CreateDate,
      @Creator,
      @EditDate,
      @Editor,
      @Version)
    </ifarray>
  </insert>

  <select id="qryResourceRoot">
    select a.* from resource as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="GroupSort" then="and">
        a.GroupSort = @GroupSort
      </ifnotnull>
      <ifarray parameter = "GroupSortArray" open="" close="" split="," then="and">
        a.GroupSort in (@GroupSortArray)
      </ifarray>
    </if>
  </select>

  <update id="updateResourceRoot">
    update resource
    set Version = Version + 1,
    ActionDescn = @ActionDescn,
    EditDate = @EditDate,
    Editor = @Editor
    where AggregateId = @AggregateId;
  </update>

  <update id="batchUpdateResourceRoot">
    <ifarray open="" close="" parameter="" split="" then="">
      update resource
      set Version = Version + 1,
      GroupSort = @GroupSort,
      ActionDescn = @ActionDescn,
      EditDate = @EditDate,
      Editor = @Editor
      where AggregateId = @AggregateId;
    </ifarray>
  </update>

  <delete id="deleteResourceRoot">
    delete from resource
    where AggregateId = @AggregateId;
  </delete>

  <delete id="batchDeleteResourceRoot">
    <ifarray open="" close="" parameter="" split="" then="">
      delete resource
      from resource
      where AggregateId = @AggregateId;
    </ifarray>
  </delete>
</namespace>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/Permissions/Repository/Xml/SqlServer/DepartmentResource.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="sqlserver" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <insert id="batchInsertDepartmentResourceRoot">
    insert into department_resource
    (AggregateId,
    DepartmentId,
    ResourceId,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    <ifarray open="" close="" parameter="" split="," then="">
      (@AggregateId,
      @DepartmentId,
      @ResourceId,
      @CreateDate,
      @Creator,
      @EditDate,
      @Editor,
      @Version)
    </ifarray>
  </insert>

  <select id="qryDepartmentResourceRoot">
    select dr.* from resource as a inner join department_resource as dr on a.AggregateId = dr.ResourceId
    where dr.DepartmentId = @DepartmentId
    and a.GroupSort = 0;
  </select>
  
  <select id="qryResourceRootOfDepartment">
    select a.* from resource as a inner join department_resource as dr on a.AggregateId = dr.ResourceId
    where dr.DepartmentId = @DepartmentId
    and a.GroupSort = 0;
  </select>
  
  <select id="qryDepartmentOwnerResourceRoot">
    select a.*,
    (select DepartmentId from department_resource as dr where a.AggregateId = dr.ResourceId and dr.DepartmentId = @DepartmentId) as OwnerId
    from resource as a
    where a.GroupSort = 0;
  </select>
  
  <delete id="deleteDepartmentResourceRoot">
    delete from department_resource
    where AggregateId = @AggregateId;
  </delete>

  <delete id="batchDeleteDepartmentResourceRoot">
    delete from department_resource
    <if then="where" end="" split="">
      <ifarray open="" close="" parameter="AggregateId" split="," then="">
        AggregateId in (@AggregateId)
      </ifarray>
      <ifarray open="" close="" parameter="ResourceId" split="," then="">
        ResourceId in (@ResourceId)
      </ifarray>
    </if>
  </delete>
</namespace>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/Permissions/Repository/Xml/MySql/EmployeeGroup.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="mysql" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <insert id="batchInsertEmployeeGroupRoot">
    insert into employee_group
    (AggregateId,
    EmployeeId,
    GroupId,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    <ifarray open="" close="" parameter="" split="," then="">
      (@AggregateId,
      @EmployeeId,
      @GroupId,
      @CreateDate,
      @Creator,
      @EditDate,
      @Editor,
      @Version)
    </ifarray>
  </insert>

  <select id="qryEmployeeGroupRoot">
    select a.* from employee_group as a
    <if then="where" end="" split="">
      <ifnotnull parameter="GroupId" then="and">
        a.GroupId = @GroupId
      </ifnotnull>
      <ifnotnull parameter="EmployeeId" then="and">
        a.EmployeeId = @EmployeeId
      </ifnotnull>
    </if>
  </select>

  <delete id="deleteEmployeeGroupRoot">
    delete from employee_group
    where AggregateId = @AggregateId;
  </delete>

  <delete id="batchDeleteEmployeeGroupRoot">
    delete from employee_group
    <ifarray open="" close="" parameter="AggregateId" split="," then="">
      where AggregateId in (@AggregateId);
    </ifarray>
  </delete>

  <select id="qryEmployeeResourceRoot">
    select a.* from resource as a inner join group_resource as gr on a.AggregateId = gr.ResourceId inner join employee_group as eg on eg.GroupId = gr.GroupId
    where eg.EmployeeId = @EmployeeId;
  </select>

  <select id="qryEmployeeOwnerGroupRoot">
    select a.*,
    (select EmployeeId from employee_group as eg where a.AggregateId = eg.GroupId and eg.EmployeeId = @EmployeeId) as OwnerId
    from `group` as a
    where a.DepartmentId = @DepartmentId
  </select>
</namespace>

=== shelldudu/never_application/src/message/B2C.Message.SqlData/Query/Xml/SqlServer/EmailCodeQuery.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="sqlserver.query" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <sql id="qryEmailCodeInfoScout">
    <ifnotnull parameter="AggregateId" then="and">
      a.AggregateId = @AggregateId
    </ifnotnull>
    <ifnotnull parameter="Email" then="and">
      a.Email = @Email
    </ifnotnull>
    <ifnotnull parameter="UsageType" then="and">
      a.UsageType = @UsageType
    </ifnotnull>
    <ifnotnull parameter="UsageStatus" then="and">
      a.UsageStatus= @UsageStatus
    </ifnotnull>
  </sql>

  
  <select id="qry_EmailCodeInfo">
    select p.* from (select row_number() over (
    <ifnotnull parameter="OrderBy" then="">
      $OrderBy$
    </ifnotnull>
    <ifnull parameter="OrderBy" then="">
      order by a.Id desc
    </ifnull>
    ) as _,   a.* from email_code as a
    <if then="where" end="" split="">
      <include refid="qryTemplateInfoScout"></include>
    </if>
    ) as p where p._ >= @StartIndex and p._ &lt;= @EndIndex
  </select>

</namespace>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/Permissions/Repository/Xml/MySql/Group.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="mysql" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <insert id="insertGroupRoot">
    insert into `group`
    (AggregateId,
    DepartmentId,
    Name,
    Descn,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    (@AggregateId,
    @DepartmentId,
    @Name,
    @Descn,
    @CreateDate,
    @Creator,
    @EditDate,
    @Editor,
    @Version);
    <return type="int">
      select last_insert_id() as Id;
    </return>
  </insert>

  <select id="qryGroupRoot">
    select a.* from `group` as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
      <ifnotnull parameter="DepartmentId" then="and">
        a.DepartmentId = @DepartmentId
      </ifnotnull>
    </if>
  </select>

  <select id="qry_GroupRoot">
    select a.* from `group` as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
      <ifnotnull parameter="DepartmentId" then="and">
        a.DepartmentId = @DepartmentId
      </ifnotnull>
    </if>
    order by id desc
    limit @StartIndex,@PageSize
  </select>
  
  <select id="qryGroupRootCount">
    select count(a.Id) from `group` as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
      <ifnotnull parameter="DepartmentId" then="and">
        a.DepartmentId = @DepartmentId
      </ifnotnull>
    </if>
  </select>

  <update id="updateGroupRoot">
    update `group`
    set Version = Version + 1,
    Name = @Name,
    Descn = @Descn,
    EditDate = @EditDate,
    Editor = @Editor
    where AggregateId = @AggregateId
    and Version = @Version;
  </update>

  <delete id="deleteGroupRoot">
    delete from `group`
    where AggregateId = @AggregateId
    and Version = @Version;
  </delete>

  <delete id="batchDeleteGroupRoot">
    <ifarray open="" close="" parameter="" split="" then="">
      delete from `group`
      where AggregateId = @AggregateId
      and Version = @Version;
    </ifarray>
  </delete>
</namespace>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/Permissions/Repository/Xml/Sqlite/Department.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="sqlite" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <insert id="insertDepartmentRoot">
    insert into department
    (AggregateId,
    Name,
    Descn,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    (@AggregateId,
    @Name,
    @Descn,
    @CreateDate,
    @Creator,
    @EditDate,
    @Editor,
    @Version);
    <return type="int">
      select last_insert_rowid() as Id;
    </return>
  </insert>

  <select id="qryDepartmentRoot">
    select a.* from department as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
    </if>
  </select>

  <select id="qry_DepartmentRoot">
    select a.* from department as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
    </if>
    order by id desc
    limit @StartIndex,@PageSize
  </select>

  <select id="qryDepartmentRootCount">
    select count(a.Id) from department as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="Name" then="and">
        a.Name = @Name
      </ifnotnull>
    </if>
  </select>

  <update id="updateDepartmentRoot">
    update department
    set Version = Version + 1,
    Name = @Name,
    Descn = @Descn,
    EditDate = @EditDate,
    Editor = @Editor
    where AggregateId = @AggregateId
    and Version = @Version;
  </update>

  <delete id="deleteDepartmentRoot">
    delete from department
    where AggregateId = @AggregateId
    and Version = @Version;
  </delete>
</namespace>

=== shelldudu/never_application/src/admin/B2C.Admin.Web/Permissions/Repository/Xml/SqlServer/Employee.xml
<?xml version="1.0" encoding="utf-8" ?>
<namespace id="sqlserver" indented="true" xmlns="never.easysql" xsi:schemaLocation="never.easysql ../../../../App_Config/easysql.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <insert id="insertEmployeeRoot">
    insert into employee
    (AggregateId,
    UserName,
    Password,
    NickName,
    DepartmentId,
    GroupSort,
    CreateDate,
    Creator,
    EditDate,
    Editor,
    Version)
    values
    (@AggregateId,
    @UserName,
    @Password,
    @NickName,
    @DepartmentId,
    @GroupSort,
    @CreateDate,
    @Creator,
    @EditDate,
    @Editor,
    @Version);
    <return type="int">
      select @@Identity;
    </return>
  </insert>

  <select id="qryEmployeeRoot">
    select a.* from employee as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="UserName" then="and">
        a.UserName = @UserName
      </ifnotnull>
      <ifnotnull parameter="DepartmentId" then="and">
        a.DepartmentId = @DepartmentId
      </ifnotnull>
    </if>
  </select>
  
  <select id="qry_EmployeeRoot">
   select p.* from (select row_number() over (order by id desc) as _, a.* from employee as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="UserName" then="and">
        a.UserName = @UserName
      </ifnotnull>
      <ifnotnull parameter="DepartmentId" then="and">
        a.DepartmentId = @DepartmentId
      </ifnotnull>
    </if>
    ) as p where p._ >= @StartIndex and p._ &lt;= @EndIndex
  </select>
  
  <select id="qryEmployeeRootCount">
    select count(a.Id) from employee as a
    <if then="where" split="" end="">
      <ifnotnull parameter="AggregateId" then="and">
        a.AggregateId = @AggregateId
      </ifnotnull>
      <ifnotnull parameter="UserName" then="and">
        a.UserName = @UserName
      </ifnotnull>
      <ifnotnull parameter="DepartmentId" then="and">
        a.DepartmentId = @DepartmentId
      </ifnotnull>
    </if>
  </select>
  
  <select id="qryEmployeeRootUsingGroup">
    select a.* from employee as a inner join employee_group as dr on a.AggregateId = dr.EmployeeId
    where dr.GroupId = @GroupId;
  </select>
  
  <update id="updateEmployeeRoot">
    update employee
    set Version = Version + 1,
    Password = @Password,
    NickName = @NickName,
    DepartmentId = @DepartmentId,
    GroupSort = @GroupSort,
    EditDate = @EditDate,
    Editor = @Editor
    where AggregateId = @AggregateId
    and Version = @Version;
  </update>

  <delete id="deleteEmployeeRoot">
    delete from employee
    where AggregateId = @AggregateId
    and Version = @Version;
  </delete>
</namespace>
